name: Generate_Docker_Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-sub-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Fetch Wipter .deb and extract version
        id: version_check
        run: |
          mkdir -p /tmp/wipter
          cd /tmp/wipter
          curl -sL https://provider-assets.wipter.com/latest/linux/x64/wipter-app-amd64.deb -o wipter-app-amd64.deb
          latest=$(dpkg-deb -f wipter-app-amd64.deb Version)
          echo "latest=$latest" >> $GITHUB_OUTPUT

          if [[ -f "$GITHUB_WORKSPACE/version.txt" ]]; then
            stored=$(<"$GITHUB_WORKSPACE/version.txt")
          else
            stored=""
          fi
          echo "stored=$stored" >> $GITHUB_OUTPUT

          if [[ "$latest" != "$stored" ]]; then
            echo "$latest" > "$GITHUB_WORKSPACE/version.txt"
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit version.txt back to main
        if: steps.version_check.outputs.update_needed == 'true'
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git add version.txt
          git commit -m "Update version.txt to ${{ steps.version_check.outputs.latest }} [skip ci]"
          git remote set-url origin https://techroy23:${{ secrets.GH_PAT }}@github.com/techroy23/Docker-Wipter.git
          git push origin main

      - name: Set up QEMU
        if: steps.version_check.outputs.update_needed == 'true'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set Up Docker Buildx
        if: steps.version_check.outputs.update_needed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: steps.version_check.outputs.update_needed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Log in to Docker Hub
        if: steps.version_check.outputs.update_needed == 'true'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push image to GHCR & Docker Hub
        if: steps.version_check.outputs.update_needed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/docker-wipter:${{ steps.version_check.outputs.latest }}
            ghcr.io/${{ github.repository_owner }}/docker-wipter:latest
            docker.io/techroy23/docker-wipter:${{ steps.version_check.outputs.latest }}
            docker.io/techroy23/docker-wipter:latest